### ISSUE TITLE
Support conversion from LLA to ENU (or NED) and back

### ISSUE THREAD

**Issue by fintelia** [DaveKram/coord_transforms#2]
Are there any plans to support these conversions?

**Comment by DaveKram** [comment]
Are you talking about converting an LLA to NED/ENU given a local LLA origin? That wouldn't be too difficult to add I would think. 

Something like Matlab's [geodetic2ned](https://www.mathworks.com/help/map/ref/geodetic2ned.html)?

**Comment by fintelia** [comment]
Yeah, that's what I had in mind

**Comment by DaveKram** [comment]
Alright, I'm going to take a look at this tonight - if I can get something working I'll also do a crates.io release alongside it.

**Comment by DaveKram** [comment]
LLA2NED and LLA2ENU are added in [c85ba11](https://github.com/DaveKram/coord_transforms/commit/c85ba11c42917dbcf20346e12219fc82f42c907d)

These are done by converting your LLA origin + LLA actual point to ECEF and using the NED/ENU rotation matrix respectively applied to (actual_ecef - origin_ecef)

**Comment by DaveKram** [comment]
I'll be working on the other way (NED2LLA and ENU2LLA) in a little while.

**Comment by DaveKram** [comment]
NED2LLA and ENU2LLA are supported int [4690d2b](https://github.com/DaveKram/coord_transforms/commit/4690d2be5d4bd1fe578d387f2b6e4a95837699a3)

I'll be making a release of this version on Github and on crates.io. It has also passed the Travis CI build tests.

Thanks for the suggestions! Closing this now. Let me know if you use this/have issues. Been kind of busy recently so I'm hoping my math is right :) Matlab seems to think so.
