### ISSUE TITLE
UTM to LL subtract overflow

### ISSUE THREAD

**Issue by ktmattson-alion** [DaveKram/coord_transforms#7]
this line in geo.rs `let lambda0 = (((z - 1) * 6 - 180 + 3) as f64).to_radians();` fails for all UTM zones < 31

it should be `let lambda0 = (((z as i32 - 1) * 6 - 180 + 3) as f64).to_radians();` or zone could be i32

**Comment by DaveKram** [comment]
Good catch. Fixed in [15e04c0](https://github.com/DaveKram/coord_transforms/commit/15e04c0e5caf5eff100ce1a8af1be6dd695a8436#diff-a82d90644bb5b6ecebf3bd6ab07bb5bacb6868ab2221bbe2fd8bf37e1a7c3735)

I'm going to bump the version to 1.3.1 and bump on crates.io
